### PR TITLE
Updated verify related items details if no resources are found

### PR DESCRIPTION
**Pull request by dislbenn**
Related issue: https://github.com/stolostron/backlog/issues/24694 & https://github.com/stolostron/backlog/issues/24814
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Review by jlpadilla — CHANGES_REQUESTED** [review]
Discussed with @dislbenn  and we want to update the implementation with this logic.

---
## CASE 1:
- KubeAPI has [A, B]
- Search has [A]

Here search is missing [B].
**Retry logic:** We wait a few seconds and call both, search and KubeAPI to confirm that either:
  - [B] was added to search.
  - [B] was deleted from KubeAPI. (Rare but could happen if other tests create resources and delete them very quickly.)
  - [B] was created after our initial check. (Rare but could happen if other tests are rapidly creating and deleting the resource).
  
**Optimization:** We can use the creation time of [B] and immediately fail if it was created more than 60 seconds ago.

## CASE 2:
- KubeAPI has [C]
- Search has [C, D]

Here search has an additional resource [D].
**Retry logic:** We wait a few seconds and call both, search and KubeAPI to confirm that either:
  - [D] was removed from search.
  - [D] was recreated after our initial check. (Rare, but could happen if other tests are rapidly creating and deleting the resource).

**Comment by dislbenn** [comment]
Closing this PR. The fix was contained within this PR: https://github.com/stolostron/search-e2e-test/pull/286.

**Pull request closed without merging**
