### PR TITLE
Updated COMPONENT_VERSION file for release-2.8

### PR DESCRIPTION
**Pull request by dislbenn**
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

Must merge https://github.com/openshift/release/pull/35425 first.

**Comment by dislbenn** [comment]
/override ci/prow/deploy-and-run-e2e

I am overriding this job to prevent the 2.8 images from being blocked from being created. There is an active PR that is opened to fix the intermittent failures that are occurring within the job: https://github.com/stolostron/search-e2e-test/pull/331.

**Pull request merged**
